# XcodeGen Project Configuration (Optional)
# This file can be used to regenerate the Xcode project if needed
# Install XcodeGen: brew install xcodegen
# Generate project: xcodegen generate

name: FindMeAppCTLTest

options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en
  
settings:
  base:
    PRODUCT_NAME: $(TARGET_NAME)
    SWIFT_VERSION: "5.0"

targets:
  FindMeAppCTLTest:
    type: application
    platform: iOS
    sources:
      - path: FindMeAppCTLTest
        excludes:
          - "*.md"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.FindMeAppCTLTest
        INFOPLIST_FILE: FindMeAppCTLTest/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    
  FindMeAppCTLTestTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: FindMeAppCTLTestTests
        excludes:
          - "*.md"
    dependencies:
      - target: FindMeAppCTLTest
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.FindMeAppCTLTestTests
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/FindMeAppCTLTest.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/FindMeAppCTLTest
  
  FindMeAppCTLTestUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: FindMeAppCTLTestUITests
        excludes:
          - "*.md"
        includes:
          - "**/*.swift"
    dependencies:
      - target: FindMeAppCTLTest
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.FindMeAppCTLTestUITests
        TEST_TARGET_NAME: FindMeAppCTLTest

schemes:
  FindMeAppCTLTest:
    build:
      targets:
        FindMeAppCTLTest: all
        FindMeAppCTLTestTests: [test]
        FindMeAppCTLTestUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - FindMeAppCTLTestTests
        - FindMeAppCTLTestUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
